language: node_js
node_js:
  - "7"
script:
  - npm run lint
  - npm run build
deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local-dir: build
  target-branch: gh-pages
  verbose: true
  on:
    branch: master
